apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: registry
spec:
  version: "v0.1.4"
  shortDescription: "A kubectl plugin to deploy a docker registry in a local Kubernetes cluster"
  description: "This plugin deploys and deletes a Docker registry in your local Kubernetes cluster."
  homepage: "https://github.com/maxyloon/registry-plugin"  # Replace with your actual homepage if available
  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: "https://github.com/maxyloon/registry-plugin/releases/download/v0.1.4/registry-plugin.tar.gz"
      sha256: "4762f39cc3d9f89a4c8e7e20e75c4cd8904895900445b5d217202dec483702ec"
      bin: kubectl-registry.sh
      files:
        - from: "*"
          to: "."